name: Build Android Debug APK

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: Create debug bundle
        run: |
          yarn bundle
      - name: Grant permissions to gradlew
        run: |
          cd android && chmod +x ./gradlew
      - name: Generate Android debug APK
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload debug build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/
